### ISSUE TITLE
Navigate husky to distant point

### ISSUE THREAD

**Issue by Federico-PizarroBejarano** [UTRA-ART/SLAM#26]
**Description**:
Currently with our navigation stack the robot does not navigate to a point that is too distant. It simply says 

```
# Logged to terminal by rviz
Invalid argument passed to canTransform argument source_frame in tf2 frame_ids cannot be empty
``` 

or 

```
# Logged to terminal by Nav Stack (move_base.launch)
Clearing costmap to unstuck robot
Rotate recovery behavior started.
Aborting because a valid plan could not be found. Even after executing all recovery behaviors
```

**Acceptance Criteria**:
You can click any point on the rviz map or put in any direction in the nav_goal and the robot will navigate to that point, regardless of how distant it is. 

**Notes**:
I would try it out, look at the errors, and look them up. Seems like a good place to start.

**Comment by erickmu1** [comment]
Seems like it may not be possible without making a large costmap: [https://answers.ros.org/question/142986/best-way-to-send-a-goal-with-move_base-that-is-off-the-global-costmap/](https://answers.ros.org/question/142986/best-way-to-send-a-goal-with-move_base-that-is-off-the-global-costmap/). But still keep looking into what configurations we may have to change in (probably) the navigation stack that would fix this issue.
What I did notice when playing with AMCL in `husky_playpen` is that I can navigate anywhere where the map is (which was everywhere since the map covered everything)
